version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - .:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      
  db:
    image: postgres:12.0-alpine
    container_name: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: insight
    volumes: 
      - "./.docker/dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  app:
    container_name: api
    build: 
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www  
  